# Generated by Django 6.0.3 on 2026-03-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('completed', models.BooleanField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
