# Generated by Django 6.0.3 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('rating', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
